### ISSUE TITLE
Da

### ISSUE THREAD

**Issue by CalvinArdiansyah18** [SattyaP/magang_smk5#4]
const {
    ipcRenderer
} = require('electron');
const start = document.getElementById('start')
const stop = document.getElementById('stop')
const files = document.getElementById('files')

document.addEventListener('change', function () {
    const files = document.getElementById('files').files[0]?.path;
    if (files == null || files == "") {
        start.setAttribute('disabled', true);
    } else if (files != "") {
        start.removeAttribute('disabled');
    }
})

start.addEventListener('click', () => {
    const data = {
        files: files.files[0]?.path
    }
    ipcRenderer.send('start', files);
});

stop.addEventListener('click', () => {
    if (confirm("Yakin a") == true) {
        ipcRenderer.send('stop');
    }
});

preload e gini a mas?

**Comment by SattyaP** [comment]
@CalvinArdiansyah18 Udah solved kah ? sorry baru liat

Kamu kalo bingung tanya langsung aja jangan diem ya , kuncinya tanya kalo diem kamu tersesad 🗿

**Comment by CalvinArdiansyah18** [comment]
> @CalvinArdiansyah18 Udah solved kah ? sorry baru liat
> 
> Kamu kalo bingung tanya langsung aja jangan diem ya , kuncinya tanya kalo diem kamu tersesad 🗿

Sudah solve mas tinggal seng tabel tadi

**Comment by CalvinArdiansyah18** [comment]
masih error koyok tadi mas yang tabel, gimana yo?

**Comment by SattyaP** [comment]
Besok aja

**Comment by CalvinArdiansyah18** [comment]
const currentItems = items.slice(i, i + 20).join('');
await page.type('#dapa_link', currentItems);
